=== jixl0224/sw/sw-study/study/src/main/resources/schema/Order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://snsoft.cn/schema/Order" xmlns="http://snsoft.cn/schema/Order" elementFormDefault="qualified">

	<xs:element name="Order" type="Order"></xs:element>

	<xs:complexType name="Order">
		<xs:sequence>
			<xs:element name="billid">
				<xs:simpleType>
					<xs:restriction base="xs:int"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="odate">
				<xs:simpleType>
					<xs:restriction base="xs:date"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="user">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="fcode">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="fcy">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="fee">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="goods" type="Good" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Good">
		<xs:sequence>
			<xs:element name="goodid">
				<xs:simpleType>
					<xs:restriction base="xs:int"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="gcode">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="unit">
				<xs:simpleType>
					<xs:restriction base="xs:string"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="upric">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="qtc">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"></xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="fcy">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"></xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== jixl0224/sw/sw-study/study/src/main/resources/schema/Order.xml
<?xml version="1.0" encoding="UTF-8"?>
<Order xmlns="http://snsoft.cn/schema/Order" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://snsoft.cn/schema/Order Order.xsd ">
  <billid>0</billid>
  <odate>2001-01-01</odate>
  <user>user</user>
  <fcode>fcode</fcode>
  <fcy>0.0</fcy>
  <fee>0.0</fee>
  <goods>
    <goodid>0</goodid>
    <gcode>gcode</gcode>
    <unit>unit</unit>
    <upric>0.0</upric>
    <qtc>0.0</qtc>
    <fcy>0.0</fcy>
  </goods>
  <goods>
    <goodid>0</goodid>
    <gcode>gcode</gcode>
    <unit>unit</unit>
    <upric>0.0</upric>
    <qtc>0.0</qtc>
    <fcy>0.0</fcy>
  </goods>
</Order>
